POST http://localhost:3003/api/blogs
Content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InB1ZzMiLCJpZCI6IjVmMTNjYTI0M2YzNmYyM2U4NmRiY2NjMCIsImlhdCI6MTU5NTEzMjQ3Nn0.mIYknHGQxoTLENOzFi6_PsdJXXr-yo9tAv4QbyZelGg

{
    "title": "pug3's note 2",
    "author": "pug3",
    "url": "xxx.yyy.zzz",
    "likes": 69,
    "userId": "5f13ca243f36f23e86dbccc0"
}