POST http://localhost:3003/api/blogs
Content-type: application/json
Authorization: bearer <token>
{
    "title": "sergey's note 3",
    "author": "sergey3",
    "url": "xxx.yyy.zzz",
    "likes": 69,
    "userId": "5f13b9f672ae3439fd694488"
}