POST http://localhost:3003/api/blogs/5f27ac091d36670cb5841c9d/comments
Content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNlcmdleSIsImlkIjoiNWYxM2I5ZjY3MmFlMzQzOWZkNjk0NDg4IiwiaWF0IjoxNTk2NDMyNzY5fQ.vVwHzdrITHwIuKmfyP9okbVTHb-EwSpKgsxy9Y_DvUE

{ "comment": "test comment 5" }