POST http://localhost:3000/api/patients/d2773822-f723-11e9-8f0b-362b9e155667/entries
Content-type: application/json

{
    "date": "2019-09-10",
    "specialist": "MD House",
    "type": "OccupationalHealthcare",
    "employerName": "FBI",
    "description": "Prescriptions renewed once again."
}